enum AppRole {
  business_owner
  customer
}

enum VerificationStatus {
  pending
  verified
  rejected
}

type Profile
  @model
  @auth(rules: [
    { allow: owner }
  ]) {
  id: ID!
  full_name: String!
  avatar_url: String

  roles: [UserRole] @hasMany(indexName: "byProfile", fields: ["id"])
  businessProfile: BusinessProfile @hasOne
}

type UserRole
  @model
  @auth(rules: [
    { allow: owner }
  ]) {
  id: ID!

  profileID: ID! @index(name: "byProfile")
  profile: Profile @belongsTo(fields: ["profileID"])

  role: AppRole!
}

type BusinessProfile
  @model
  @auth(rules: [
    { allow: owner }
  ]) {
  id: ID!

  profileID: ID!
  profile: Profile @belongsTo(fields: ["profileID"])

  business_name: String!
  category: String!
  description: String
  address: String
  phone: String
  website: String
  price_level: Int
  languages: [String]
  is_minority_owned: Boolean
  is_howard_affiliated: Boolean
  verification_status: VerificationStatus
}